/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 31-may.-2023 11:33:31 a. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

 

 

 

/* Drop Tables */

DROP TABLE IF EXISTS Cliente CASCADE
;

DROP TABLE IF EXISTS Consumo CASCADE
;

DROP TABLE IF EXISTS Cuenta CASCADE
;

DROP TABLE IF EXISTS Habitacion CASCADE
;

DROP TABLE IF EXISTS Hotel CASCADE
;

DROP TABLE IF EXISTS Huesped CASCADE
;

DROP TABLE IF EXISTS Pago CASCADE
;

DROP TABLE IF EXISTS Producto CASCADE
;

DROP TABLE IF EXISTS Registro CASCADE
;

DROP TABLE IF EXISTS Reserva CASCADE
;

DROP TABLE IF EXISTS Tipo CASCADE
;

/* Create Tables */

CREATE TABLE Cliente
(
	k_idcliente bigint NOT NULL,	-- Numero del documento de identidad que identifica univocamente a un cliente. 
	k_tipo varchar(2) NOT NULL,	-- Identificador del tipo de documento de identidad del cliente puede tomar los valores CC (Cedula de ciudadania), TI (Tarjeta de identidad), RC (Registro Civil), PS (Pasaporte).
	n_nombre1 varchar(20) NOT NULL,	-- Primer nombre del cliente.
	n_apellido1 varchar(20) NOT NULL,	-- Primer apellido del cliente.
	n_nombre2 varchar(20) NULL,	-- Segundo nombre del cliente (Opcional).
	n_apellido2 varchar(20) NULL,	-- Segundo apellido del cliente (opcional).
	o_telefono varchar(10) NOT NULL	-- Telefono de un cliente.
)
;

CREATE TABLE Consumo
(
	q_cantidad smallint NOT NULL,	-- Cantidad del producto consumido.
	f_consumo timestamp without time zone NOT NULL,	-- Fecha en la que se realizo la compra o consumo del producto.
	k_numcuenta integer NOT NULL,	-- Numero de la cuenta a la que se carga el consumo.
	k_idproducto integer NOT NULL	-- Id del producto o servicio consumido.
)
;

CREATE TABLE Cuenta
(
	k_numcuenta integer NOT NULL,	-- Identificador unico de una cuenta.
	q_valorestadia integer NOT NULL,	-- Valor total de la estadia en el hotel.
	q_valorconsumos integer NOT NULL,	-- Valor total de los productos o servicios consumidos en el hotel.
	i_estado varchar(1) NOT NULL,	-- Estado de la cuenta, puede tomar los valores E(Esperando pago) o P (Pago realizado) .
	k_numreserva serial NOT NULL	-- Numero de la reserva a la que pertenece la cuenta.
)
;

CREATE TABLE Habitacion
(
	k_numhabitacion integer NOT NULL,	-- Numero entero que identifica de forma unica una habitacion de hotel.
	k_idhotel integer NOT NULL,	-- Identificador del hotel al que pertenece la habitacion.
	k_tipohab varchar(1) NOT NULL	-- Identificador del tipo de habitacion.
)
;

CREATE TABLE Hotel
(
	k_idhotel integer NOT NULL,	-- Identificador unico del hotel.
	t_aforo numeric(2,2) NOT NULL,	-- Porcentaje de habitaciones ocupadas permitidas, debido a las restricciones por la pandemia.
	q_diasdescuento integer NOT NULL,	-- Numero minimo de dias para aplicar un descuento a una reserva.
	t_descuento numeric(2,2) NOT NULL	-- Porcentaje de descuento para la reserva.
)
;

CREATE TABLE Huesped
(
	k_idhuesped bigint NOT NULL,	-- Numero de identificacion del huesped.
	k_tipoid varchar(2) NOT NULL,	-- Identificador del tipo de documento de identidad del cliente puede tomar los valores CC (Cedula de ciudadania), TI (Tarjeta de identidad), RC (Registro Civil), PS (Pasapore).
	f_nacimiento timestamp without time zone NOT NULL,	-- Fecha de nacimiento del huesped.
	o_direccion varchar(25) NOT NULL	-- Direccion de residencia del huesped.
)
;

CREATE TABLE Pago
(
	k_idpago serial NOT NULL,	-- Numerico que identifica a un pago univocamente 
	k_numcuenta integer NOT NULL,	-- Numero de la cuenta sobre la que se paga.
	i_metodo varchar(1) NOT NULL,	-- Metodo con el que se realizo el pago, puede tomar los valores E (Efectivo) y T(Tarjeta)
	f_pago timestamp without time zone NOT NULL	-- Fecha en la que se realizo el pago.
)
;

CREATE TABLE Producto
(
	k_idproducto integer NOT NULL,	-- Identificador unico del producto o servicio.
	i_tipo varchar(1) NOT NULL,	-- Identificador del tipo de producto ofrecido por el hotel, puede tomar los valores P(Producto) o S(Servicio).
	q_valoru integer NOT NULL,	-- Valor unitario del producto o servicio.
	o_descripcion varchar(100) NOT NULL,	-- Descripcion o caracterisitcas propias del producto o servicio.
	n_nombre varchar(20) NOT NULL	-- Nombre del producto o servicio
)
;

CREATE TABLE Registro
(
	f_checkin timestamp without time zone NOT NULL,	-- Fecha de registro a la reserva.
	f_checkout timestamp without time zone NOT NULL,	-- Fecha de salida de la reserva.
	k_idhuesped integer NOT NULL,	-- Identificacion del Huesped registrado
	k_tipoid varchar(2) NOT NULL,	-- Tipo de identificacion del huesped registrado, puede tomar los valores CC (Cedula de ciudadania), TI (Tarjeta de identidad), RC (Registro Civil), PS (Pasaporte).
	k_numreserva serial NOT NULL	-- Numero consecutivo que identifica univocamente a una reserva
)
;

CREATE TABLE Reserva
(
	k_numreserva serial NOT NULL,	-- Numero consecutivo que identifica univocamente a una reserva.
	k_idcliente bigint NOT NULL,	-- Identificacion del cliente que hizo la reserva
	k_tipoid varchar(2) NOT NULL,	-- Tipo de identificacion del cliente.
	k_numhabitacion integer NOT NULL,
	i_estado varchar(2) NOT NULL,	-- Identificador del estado de la reserva, puede ser A (activa), C (cancelada), P (pendiente) o F(Finalizada).
	f_inicio timestamp without time zone NOT NULL,	-- Fecha desde la cual se reservara la habitacion.
	q_numnoches smallint NOT NULL,	-- Numero de noches que durara la reserva.
	q_numpersonas smallint NOT NULL,	-- Cantidad de personas que se hospedaran en la habitacion reservada.
	f_reserva timestamp without time zone NOT NULL	-- Fecha en la que se realizo la reserva.
)
;

CREATE TABLE Tipo
(
	k_tipo varchar(1) NOT NULL,	-- Caracter identificador de un tipo de habitacion
	q_valornoche integer NOT NULL,	-- Valor por noche del tipo de habitacion.
	o_descripcion varchar(100) NOT NULL	-- Descripcion del tipo de habitacion.
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Cliente ADD CONSTRAINT PK_Cliente
	PRIMARY KEY (k_tipo,k_idcliente)
;

ALTER TABLE Cliente ADD CONSTRAINT CK_k_tipo CHECK (k_tipo in ('CC','TI','RC','PS'))
;

ALTER TABLE Cliente ADD CONSTRAINT CK_k_idcliente CHECK (k_idcliente > 0)
;

ALTER TABLE Consumo ADD CONSTRAINT PK_Consumo
	PRIMARY KEY (k_numcuenta,k_idproducto)
;

ALTER TABLE Consumo ADD CONSTRAINT CK_q_cantidad CHECK (q_cantidad > 0)
;

ALTER TABLE Cuenta ADD CONSTRAINT PK_Cuenta
	PRIMARY KEY (k_numcuenta)
;

ALTER TABLE Cuenta ADD CONSTRAINT CK_i_estado CHECK (i_estado in ('E','P'))
;

ALTER TABLE Habitacion ADD CONSTRAINT PK_Habitacion
	PRIMARY KEY (k_numhabitacion)
;

ALTER TABLE Habitacion ADD CONSTRAINT CK_k_numhabitacion CHECK (k_numhabitacion > 0)
;

ALTER TABLE Hotel ADD CONSTRAINT PK_Hotel
	PRIMARY KEY (k_idhotel)
;

ALTER TABLE Hotel ADD CONSTRAINT CK_q_diasdescuento CHECK (q_diasdescuento > 0)
;

ALTER TABLE Hotel ADD CONSTRAINT CK_t_aforo CHECK (t_aforo > 0 AND t_aforo<=1)
;

ALTER TABLE Hotel ADD CONSTRAINT CK_t_descuento CHECK (t_descuento > 0 AND t_descuento <=1)
;

ALTER TABLE Huesped ADD CONSTRAINT PK_Huesped
	PRIMARY KEY (k_idhuesped,k_tipoid)
;

ALTER TABLE Pago ADD CONSTRAINT PK_Pago
	PRIMARY KEY (k_idpago)
;

ALTER TABLE Pago ADD CONSTRAINT CK_i_metodo CHECK (i_metodo in ('E','T'))
;

ALTER TABLE Producto ADD CONSTRAINT PK_Producto
	PRIMARY KEY (k_idproducto)
;

ALTER TABLE Producto ADD CONSTRAINT CK_k_idproducto CHECK (k_idproducto >= 0)
;

ALTER TABLE Producto ADD CONSTRAINT CK_q_valoru CHECK (q_valoru > 0)
;

ALTER TABLE Producto ADD CONSTRAINT CK_i_tipo CHECK (i_tipo in ('S','P'))
;

ALTER TABLE Registro ADD CONSTRAINT PK_Registro
	PRIMARY KEY (k_idhuesped,k_tipoid,k_numreserva)
;

ALTER TABLE Reserva ADD CONSTRAINT PK_Reserva
	PRIMARY KEY (k_numreserva)
;

ALTER TABLE Reserva ADD CONSTRAINT CK_i_estado CHECK (i_estado in ('A','P','C','F'))
;

ALTER TABLE Reserva ADD CONSTRAINT CK_q_numnoches CHECK (q_numnoches > 0)
;

ALTER TABLE Reserva ADD CONSTRAINT CK_q_numpersonas CHECK (q_numpersonas > 0)
;

ALTER TABLE Tipo ADD CONSTRAINT PK_Tipo
	PRIMARY KEY (k_tipo)
;

ALTER TABLE Tipo ADD CONSTRAINT CK_q_valornoche CHECK (q_valornoche > 0)
;

/* Create Foreign Key Constraints */

ALTER TABLE Consumo ADD CONSTRAINT FK_Consumo_Cuenta
	FOREIGN KEY (k_numcuenta) REFERENCES Cuenta (k_numcuenta) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Consumo ADD CONSTRAINT FK_Consumo_Producto
	FOREIGN KEY (k_idproducto) REFERENCES Producto (k_idproducto) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Cuenta ADD CONSTRAINT FK_Cuenta_Reserva
	FOREIGN KEY (k_numreserva) REFERENCES Reserva (k_numreserva) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Habitacion ADD CONSTRAINT FK_Habitacion_Hotel
	FOREIGN KEY (k_idhotel) REFERENCES Hotel (k_idhotel) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Habitacion ADD CONSTRAINT FK_Habitacion_Tipo
	FOREIGN KEY (k_tipohab) REFERENCES Tipo (k_tipo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Huesped ADD CONSTRAINT FK_Huesped_Cliente
	FOREIGN KEY (k_tipoid,k_idhuesped) REFERENCES Cliente (k_tipo,k_idcliente) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Pago ADD CONSTRAINT FK_Pago_Cuenta
	FOREIGN KEY (k_numcuenta) REFERENCES Cuenta (k_numcuenta) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Registro ADD CONSTRAINT FK_Registro_Huesped
	FOREIGN KEY (k_idhuesped,k_tipoid) REFERENCES Huesped (k_idhuesped,k_tipoid) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Registro ADD CONSTRAINT FK_Registro_Reserva
	FOREIGN KEY (k_numreserva) REFERENCES Reserva (k_numreserva) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Reserva ADD CONSTRAINT FK_Reserva_Cliente
	FOREIGN KEY (k_tipoid,k_idcliente) REFERENCES Cliente (k_tipo,k_idcliente) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Reserva ADD CONSTRAINT FK_Reserva_Habitacion
	FOREIGN KEY (k_numhabitacion) REFERENCES Habitacion (k_numhabitacion) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE Cliente
	IS 'Persona que hace una reserva de habitacion en el hotel.'
;

COMMENT ON COLUMN Cliente.k_idcliente
	IS 'Numero del documento de identidad que identifica univocamente a un cliente. '
;

COMMENT ON COLUMN Cliente.k_tipo
	IS 'Identificador del tipo de documento de identidad del cliente puede tomar los valores CC (Cedula de ciudadania), TI (Tarjeta de identidad), RC (Registro Civil), PS (Pasaporte).'
;

COMMENT ON COLUMN Cliente.n_nombre1
	IS 'Primer nombre del cliente.'
;

COMMENT ON COLUMN Cliente.n_apellido1
	IS 'Primer apellido del cliente.'
;

COMMENT ON COLUMN Cliente.n_nombre2
	IS 'Segundo nombre del cliente (Opcional).'
;

COMMENT ON COLUMN Cliente.n_apellido2
	IS 'Segundo apellido del cliente (opcional).'
;

COMMENT ON COLUMN Cliente.o_telefono
	IS 'Telefono de un cliente.'
;

COMMENT ON TABLE Consumo
	IS 'Registro del consumo o compra de un servicio o producto.'
;

COMMENT ON COLUMN Consumo.q_cantidad
	IS 'Cantidad del producto consumido.'
;

COMMENT ON COLUMN Consumo.f_consumo
	IS 'Fecha en la que se realizo la compra o consumo del producto.'
;

COMMENT ON COLUMN Consumo.k_numcuenta
	IS 'Numero de la cuenta a la que se carga el consumo.'
;

COMMENT ON COLUMN Consumo.k_idproducto
	IS 'Id del producto o servicio consumido.'
;

COMMENT ON TABLE Cuenta
	IS 'Cuenta a la que se cargaran el precio de la estadia y de los posibles consumos realizados.'
;

COMMENT ON COLUMN Cuenta.k_numcuenta
	IS 'Identificador unico de una cuenta.'
;

COMMENT ON COLUMN Cuenta.q_valorestadia
	IS 'Valor total de la estadia en el hotel.'
;

COMMENT ON COLUMN Cuenta.q_valorconsumos
	IS 'Valor total de los productos o servicios consumidos en el hotel.'
;

COMMENT ON COLUMN Cuenta.i_estado
	IS 'Estado de la cuenta, puede tomar los valores E(Esperando pago) o P (Pago realizado) .'
;

COMMENT ON COLUMN Cuenta.k_numreserva
	IS 'Numero de la reserva a la que pertenece la cuenta.'
;

 

COMMENT ON TABLE Habitacion
	IS 'Cuarto de Hotel apto para hospedaje.'
;

COMMENT ON COLUMN Habitacion.k_numhabitacion
	IS 'Numero entero que identifica de forma unica una habitacion de hotel.'
;

COMMENT ON COLUMN Habitacion.k_idhotel
	IS 'Identificador del hotel al que pertenece la habitacion.'
;

COMMENT ON COLUMN Habitacion.k_tipohab
	IS 'Identificador del tipo de habitacion.'
;

COMMENT ON TABLE Hotel
	IS 'Negocio principal'
;

COMMENT ON COLUMN Hotel.k_idhotel
	IS 'Identificador unico del hotel.'
;

COMMENT ON COLUMN Hotel.t_aforo
	IS 'Porcentaje de habitaciones ocupadas permitidas, debido a las restricciones por la pandemia.'
;

COMMENT ON COLUMN Hotel.q_diasdescuento
	IS 'Numero minimo de dias para aplicar un descuento a una reserva.'
;

COMMENT ON COLUMN Hotel.t_descuento
	IS 'Porcentaje de descuento para la reserva.'
;

COMMENT ON TABLE Huesped
	IS 'Cliente que se hospeda en una habitacion de hotel reservada.'
;

COMMENT ON COLUMN Huesped.k_idhuesped
	IS 'Numero de identificacion del huesped.'
;

COMMENT ON COLUMN Huesped.k_tipoid
	IS 'Identificador del tipo de documento de identidad del cliente puede tomar los valores CC (Cedula de ciudadania), TI (Tarjeta de identidad), RC (Registro Civil), PS (Pasapore).'
;

COMMENT ON COLUMN Huesped.f_nacimiento
	IS 'Fecha de nacimiento del huesped.'
;

COMMENT ON COLUMN Huesped.o_direccion
	IS 'Direccion de residencia del huesped.'
;

COMMENT ON TABLE Pago
	IS 'Informacion del pago realizado por los estadia y consumos realizados durante el hospedaje.'
;

COMMENT ON COLUMN Pago.k_idpago
	IS 'Numerico que identifica a un pago univocamente '
;

COMMENT ON COLUMN Pago.k_numcuenta
	IS 'Numero de la cuenta sobre la que se paga.'
;

COMMENT ON COLUMN Pago.i_metodo
	IS 'Metodo con el que se realizo el pago, puede tomar los valores E (Efectivo) y T(Tarjeta)'
;

COMMENT ON COLUMN Pago.f_pago
	IS 'Fecha en la que se realizo el pago.'
;

 

COMMENT ON TABLE Producto
	IS 'Producto o servicio ofrecido por el hotel.'
;

COMMENT ON COLUMN Producto.k_idproducto
	IS 'Identificador unico del producto o servicio.'
;

COMMENT ON COLUMN Producto.i_tipo
	IS 'Identificador del tipo de producto ofrecido por el hotel, puede tomar los valores P(Producto) o S(Servicio).'
;

COMMENT ON COLUMN Producto.q_valoru
	IS 'Valor unitario del producto o servicio.'
;

COMMENT ON COLUMN Producto.o_descripcion
	IS 'Descripcion o caracterisitcas propias del producto o servicio.'
;

COMMENT ON COLUMN Producto.n_nombre
	IS 'Nombre del producto o servicio'
;

COMMENT ON TABLE Registro
	IS 'Registra la entrada y salida de un huesped a una reserva.'
;

COMMENT ON COLUMN Registro.f_checkin
	IS 'Fecha de registro a la reserva.'
;

COMMENT ON COLUMN Registro.f_checkout
	IS 'Fecha de salida de la reserva.'
;

COMMENT ON COLUMN Registro.k_idhuesped
	IS 'Identificacion del Huesped registrado'
;

COMMENT ON COLUMN Registro.k_tipoid
	IS 'Tipo de identificacion del huesped registrado, puede tomar los valores CC (Cedula de ciudadania), TI (Tarjeta de identidad), RC (Registro Civil), PS (Pasaporte).'
;

COMMENT ON COLUMN Registro.k_numreserva
	IS 'Numero consecutivo que identifica univocamente a una reserva'
;

 

COMMENT ON TABLE Reserva
	IS 'Agendamiento de una habitacion del hotel que inicia en una fecha en especifico.'
;

COMMENT ON COLUMN Reserva.k_numreserva
	IS 'Numero consecutivo que identifica univocamente a una reserva.'
;

COMMENT ON COLUMN Reserva.k_idcliente
	IS 'Identificacion del cliente que hizo la reserva'
;

COMMENT ON COLUMN Reserva.k_tipoid
	IS 'Tipo de identificacion del cliente.'
;

COMMENT ON COLUMN Reserva.i_estado
	IS 'Identificador del estado de la reserva, puede ser A (activa), C (cancelada), P (pendiente) o F(Finalizada).'
;

COMMENT ON COLUMN Reserva.f_inicio
	IS 'Fecha desde la cual se reservara la habitacion.'
;

COMMENT ON COLUMN Reserva.q_numnoches
	IS 'Numero de noches que durara la reserva.'
;

COMMENT ON COLUMN Reserva.q_numpersonas
	IS 'Cantidad de personas que se hospedaran en la habitacion reservada.'
;

COMMENT ON COLUMN Reserva.f_reserva
	IS 'Fecha en la que se realizo la reserva.'
;

 

COMMENT ON TABLE Tipo
	IS 'Tipo de habitacion.'
;

COMMENT ON COLUMN Tipo.k_tipo
	IS 'Caracter identificador de un tipo de habitacion'
;

COMMENT ON COLUMN Tipo.q_valornoche
	IS 'Valor por noche del tipo de habitacion.'
;

COMMENT ON COLUMN Tipo.o_descripcion
	IS 'Descripcion del tipo de habitacion.'
;
